import { DataSource } from 'typeorm';
import { config } from 'dotenv';
import { Food } from '../food/food.entity';
import { Participants } from '../participants/participants.entity';
import { Preference } from '../preference/preference.entity';
import { Room } from '../room/room.entity';

config();

const AppDataSource = new DataSource({
  type: 'mysql',
  host: process.env.DB_HOST,
  port: Number(process.env.DB_PORT),
  username: process.env.DB_USERNAME,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
  entities: [Food, Preference, Participants, Room],
  synchronize: true,
});

const foodCatalog = [
  {
    name: '김치찌개',
    description: '매콤한 김치와 돼지고기를 넣어 푹 끓인 한국 전통 찌개',
    imageUrl: 'https://example.com/kimchi_jjigae.jpg',
    category: 'korean',
    mealTimes: ['lunch', 'dinner'],
    minBudget: 9000,
    maxBudget: 12000,
    spiceLevel: 2,
    quickMeal: true,
    shareable: false,
    deliveryFriendly: true,
  },
  {
    name: '된장찌개',
    description: '구수한 된장에 두부와 채소를 넣어 끓인 한국식 찌개',
    imageUrl: 'https://example.com/doenjang_jjigae.jpg',
    category: 'korean',
    mealTimes: ['lunch', 'dinner'],
    minBudget: 9000,
    maxBudget: 12000,
    spiceLevel: 0,
    quickMeal: true,
    shareable: false,
    deliveryFriendly: true,
  },
  {
    name: '비빔밥',
    description: '여러 가지 나물과 고추장, 계란을 밥에 비벼 먹는 한 그릇 요리',
    imageUrl: 'https://example.com/bibimbap.jpg',
    category: 'korean',
    mealTimes: ['lunch', 'dinner'],
    minBudget: 9000,
    maxBudget: 13000,
    spiceLevel: 1,
    quickMeal: true,
    shareable: false,
    deliveryFriendly: true,
  },
  {
    name: '불고기',
    description: '달콤짭짤한 양념에 재운 얇게 썬 소고기를 구워 먹는 한국식 고기 요리',
    imageUrl: 'https://example.com/bulgogi.jpg',
    category: 'meat',
    mealTimes: ['dinner'],
    minBudget: 14000,
    maxBudget: 22000,
    spiceLevel: 0,
    quickMeal: false,
    shareable: true,
    deliveryFriendly: true,
  },
  {
    name: '삼겹살',
    description: '두툼한 돼지고기 삼겹 부위를 구워 쌈과 함께 즐기는 고기 요리',
    imageUrl: 'https://example.com/samgyeopsal.jpg',
    category: 'meat',
    mealTimes: ['dinner'],
    minBudget: 17000,
    maxBudget: 25000,
    spiceLevel: 0,
    quickMeal: false,
    shareable: true,
    deliveryFriendly: false,
  },
  {
    name: '순두부찌개',
    description: '부드러운 순두부와 해산물, 고추기름을 넣어 끓인 얼큰한 찌개',
    imageUrl: 'https://example.com/soondubu_jjigae.jpg',
    category: 'korean',
    mealTimes: ['lunch', 'dinner'],
    minBudget: 9000,
    maxBudget: 12000,
    spiceLevel: 2,
    quickMeal: true,
    shareable: false,
    deliveryFriendly: true,
  },
  {
    name: '갈비탕',
    description: '소갈비와 무를 넣어 맑게 끓여낸 담백한 국물 요리',
    imageUrl: 'https://example.com/galbitang.jpg',
    category: 'korean',
    mealTimes: ['lunch', 'dinner'],
    minBudget: 13000,
    maxBudget: 17000,
    spiceLevel: 0,
    quickMeal: false,
    shareable: false,
    deliveryFriendly: true,
  },
  {
    name: '냉면',
    description: '차가운 육수에 메밀면 또는 소면을 말아 시원하게 먹는 면 요리',
    imageUrl: 'https://example.com/naengmyeon.jpg',
    category: 'korean',
    mealTimes: ['lunch', 'dinner'],
    minBudget: 10000,
    maxBudget: 14000,
    spiceLevel: 0,
    quickMeal: true,
    shareable: false,
    deliveryFriendly: false,
  },
  {
    name: '떡볶이',
    description: '가래떡과 어묵을 고추장 양념에 매콤하게 볶아낸 길거리 음식',
    imageUrl: 'https://example.com/tteokbokki.jpg',
    category: 'fastfood',
    mealTimes: ['lunch', 'late-night'],
    minBudget: 6000,
    maxBudget: 10000,
    spiceLevel: 2,
    quickMeal: true,
    shareable: true,
    deliveryFriendly: true,
  },
  {
    name: '마파두부',
    description:
      '부드러운 두부와 매콤한 고추기름, 다진 돼지고기를 넣어 만든 중국 쓰촨식 요리',
    imageUrl: 'https://example.com/mapo_tofu.jpg',
    category: 'chinese',
    mealTimes: ['lunch', 'dinner'],
    minBudget: 11000,
    maxBudget: 16000,
    spiceLevel: 3,
    quickMeal: false,
    shareable: true,
    deliveryFriendly: true,
  },
  {
    name: '탕수육',
    description: '바삭하게 튀긴 돼지고기를 달콤새콤한 소스에 버무린 중국식 요리',
    imageUrl: 'https://example.com/tangsuyuk.jpg',
    category: 'chinese',
    mealTimes: ['lunch', 'dinner'],
    minBudget: 17000,
    maxBudget: 26000,
    spiceLevel: 0,
    quickMeal: false,
    shareable: true,
    deliveryFriendly: true,
  },
  {
    name: '짜장면',
    description: '춘장 소스로 볶은 돼지고기와 채소를 얹어 먹는 중화풍 면 요리',
    imageUrl: 'https://example.com/jjajangmyeon.jpg',
    category: 'chinese',
    mealTimes: ['lunch', 'dinner'],
    minBudget: 7000,
    maxBudget: 10000,
    spiceLevel: 0,
    quickMeal: true,
    shareable: false,
    deliveryFriendly: true,
  },
  {
    name: '짬뽕',
    description: '매운 해산물 육수에 각종 해산물과 야채를 넣어 끓인 중화풍 면 요리',
    imageUrl: 'https://example.com/jjamppong.jpg',
    category: 'chinese',
    mealTimes: ['lunch', 'dinner'],
    minBudget: 9000,
    maxBudget: 12000,
    spiceLevel: 2,
    quickMeal: true,
    shareable: false,
    deliveryFriendly: true,
  },
  {
    name: '스시',
    description: '식초 밥 위에 생선이나 해산물을 얹어 만든 일본 전통 초밥',
    imageUrl: 'https://example.com/sushi.jpg',
    category: 'japanese',
    mealTimes: ['lunch', 'dinner'],
    minBudget: 15000,
    maxBudget: 24000,
    spiceLevel: 0,
    quickMeal: false,
    shareable: false,
    deliveryFriendly: false,
  },
  {
    name: '돈카츠',
    description: '두툼한 돼지고기 커틀릿을 빵가루로 튀겨 소스와 함께 즐기는 일본식 요리',
    imageUrl: 'https://example.com/tonkatsu.jpg',
    category: 'japanese',
    mealTimes: ['lunch', 'dinner'],
    minBudget: 10000,
    maxBudget: 14000,
    spiceLevel: 0,
    quickMeal: true,
    shareable: false,
    deliveryFriendly: true,
  },
  {
    name: '라멘',
    description: '진한 육수와 쫄깃한 면발, 차슈와 계란을 곁들인 일본식 국수',
    imageUrl: 'https://example.com/ramen.jpg',
    category: 'japanese',
    mealTimes: ['lunch', 'dinner', 'late-night'],
    minBudget: 10000,
    maxBudget: 14000,
    spiceLevel: 1,
    quickMeal: true,
    shareable: false,
    deliveryFriendly: true,
  },
  {
    name: '우동',
    description: '쫄깃한 굵은 면발을 맑은 육수에 말아 간단하게 즐기는 일본식 국수',
    imageUrl: 'https://example.com/udon.jpg',
    category: 'japanese',
    mealTimes: ['lunch', 'dinner'],
    minBudget: 8000,
    maxBudget: 11000,
    spiceLevel: 0,
    quickMeal: true,
    shareable: false,
    deliveryFriendly: true,
  },
  {
    name: '스테이크',
    description: '두툼한 소고기를 원하는 굽기로 구워 소스와 함께 즐기는 서양식 메인 요리',
    imageUrl: 'https://example.com/steak.jpg',
    category: 'western',
    mealTimes: ['dinner'],
    minBudget: 22000,
    maxBudget: 38000,
    spiceLevel: 0,
    quickMeal: false,
    shareable: false,
    deliveryFriendly: false,
  },
  {
    name: '카르보나라 파스타',
    description: '크림과 베이컨, 치즈를 섞어 만든 부드러운 이탈리아식 크림 파스타',
    imageUrl: 'https://example.com/carbonara.jpg',
    category: 'western',
    mealTimes: ['lunch', 'dinner'],
    minBudget: 13000,
    maxBudget: 18000,
    spiceLevel: 0,
    quickMeal: false,
    shareable: false,
    deliveryFriendly: true,
  },
  {
    name: '마르게리타 피자',
    description:
      '토마토 소스, 모짜렐라 치즈, 바질을 올린 간단한 이탈리아 정통 피자',
    imageUrl: 'https://example.com/margherita.jpg',
    category: 'western',
    mealTimes: ['lunch', 'dinner', 'late-night'],
    minBudget: 18000,
    maxBudget: 26000,
    spiceLevel: 0,
    quickMeal: false,
    shareable: true,
    deliveryFriendly: true,
  },
  {
    name: '치즈버거',
    description: '패티와 치즈, 채소를 번 사이에 끼워 만든 미국식 햄버거',
    imageUrl: 'https://example.com/cheeseburger.jpg',
    category: 'fastfood',
    mealTimes: ['lunch', 'dinner'],
    minBudget: 8000,
    maxBudget: 12000,
    spiceLevel: 0,
    quickMeal: true,
    shareable: false,
    deliveryFriendly: true,
  },
  {
    name: '타코',
    description: '옥수수 토르티야에 고기와 채소, 살사를 올려 먹는 멕시코식 요리',
    imageUrl: 'https://example.com/taco.jpg',
    category: 'western',
    mealTimes: ['lunch', 'dinner'],
    minBudget: 9000,
    maxBudget: 14000,
    spiceLevel: 2,
    quickMeal: true,
    shareable: true,
    deliveryFriendly: true,
  },
  {
    name: '버터 치킨',
    description: '토마토 크림 소스에 부드러운 닭고기를 넣어 만든 인도식 커리',
    imageUrl: 'https://example.com/butter_chicken.jpg',
    category: 'asian',
    mealTimes: ['lunch', 'dinner'],
    minBudget: 12000,
    maxBudget: 17000,
    spiceLevel: 1,
    quickMeal: false,
    shareable: true,
    deliveryFriendly: true,
  },
  {
    name: '팟타이',
    description:
      '쌀국수에 새우와 두부, 땅콩, 숙주를 넣고 달콤새콤하게 볶아낸 태국식 면 요리',
    imageUrl: 'https://example.com/pad_thai.jpg',
    category: 'asian',
    mealTimes: ['lunch', 'dinner'],
    minBudget: 10000,
    maxBudget: 14000,
    spiceLevel: 1,
    quickMeal: true,
    shareable: false,
    deliveryFriendly: true,
  },
  {
    name: '쌀국수',
    description: '맑은 육수와 가벼운 고명을 곁들여 부담 없이 먹기 좋은 베트남식 면 요리',
    imageUrl: 'https://example.com/pho.jpg',
    category: 'asian',
    mealTimes: ['lunch', 'dinner'],
    minBudget: 9000,
    maxBudget: 13000,
    spiceLevel: 0,
    quickMeal: true,
    shareable: false,
    deliveryFriendly: true,
  },
  {
    name: '치킨',
    description: '배달과 모임에 모두 잘 어울리는 대표적인 공유 메뉴',
    imageUrl: 'https://example.com/chicken.jpg',
    category: 'fastfood',
    mealTimes: ['dinner', 'late-night'],
    minBudget: 18000,
    maxBudget: 26000,
    spiceLevel: 1,
    quickMeal: false,
    shareable: true,
    deliveryFriendly: true,
  },
  {
    name: '족발',
    description: '여럿이 함께 먹기 좋고 저녁 모임에 어울리는 대표적인 한식 메뉴',
    imageUrl: 'https://example.com/jokbal.jpg',
    category: 'meat',
    mealTimes: ['dinner', 'late-night'],
    minBudget: 28000,
    maxBudget: 38000,
    spiceLevel: 0,
    quickMeal: false,
    shareable: true,
    deliveryFriendly: true,
  },
];

async function seedFoodMetadata() {
  await AppDataSource.initialize();

  const foodRepo = AppDataSource.getRepository(Food);
  let createdCount = 0;
  let updatedCount = 0;

  for (const food of foodCatalog) {
    const existing = await foodRepo.findOne({
      where: { name: food.name },
    });

    if (existing) {
      await foodRepo.save({
        ...existing,
        ...food,
      });
      updatedCount += 1;
      continue;
    }

    await foodRepo.save(foodRepo.create(food));
    createdCount += 1;
  }

  console.log(
    `food metadata seed completed: created=${createdCount}, updated=${updatedCount}`,
  );
  await AppDataSource.destroy();
}

seedFoodMetadata()
  .then(() => process.exit(0))
  .catch(async (error) => {
    console.error(error);
    if (AppDataSource.isInitialized) {
      await AppDataSource.destroy();
    }
    process.exit(1);
  });
